[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev", "clippy", "rustfmt", "cargo", "rust-analyzer"]
targets = [ "aarch64-apple-darwin", "x86_64-unknown-linux-musl",  "x86_64-unknown-linux-gnu", "wasm32-wasi" ]
profile = "default"
